### ISSUE TITLE
打包后，打开index.html 显示空白页是怎么了？

### ISSUE THREAD

**Issue by ajnudnyy** [zhaotoday/react-antd-mobile#4]
急急急!!  
领导啊， 我用你这个项目作为基础  实现我我们公司的一个html5 页面， 但是开发完之后打包成静态文件直接点开index.html  只显示空白页 ， 之前开发的内容完全没有，怎么办？

**Comment by ajnudnyy** [comment]
求领导指点指点我一下

**Comment by ajnudnyy** [comment]
你看所有打包文件都引入进来了，但是页面就是没有渲染

**Comment by zhaotoday** [comment]
用服务器环境访问，可以用 http-server 在根目录下执行 http-server -p 88，然后访问 http://localhost:88。

**Comment by ajnudnyy** [comment]
![image](https://user-images.githubusercontent.com/18208441/29104214-bc61f65c-7cf6-11e7-86d6-22fdd865683c.png)

![image](https://user-images.githubusercontent.com/18208441/29104230-d3136106-7cf6-11e7-96f8-9ef9875d6c8a.png)

**Comment by ajnudnyy** [comment]
不支持静态访问吗？
